version: '3.8'
services:
  # Infra (optional in prod, you can omit if running infra elsewhere)
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: ["2181:2181"]

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: ["9092:9092"]
    depends_on: [zookeeper]

  mongodb:
    image: mongo:6
    ports: ["27018:27017"]

  # Microservices – Dev builds and Prod images
  alert-generator:
    build:
      context: "./Alert Management/alert-generator-service"
    image: myregistry.com/deas-la/alert-generator-service:latest
    ports: ["8000:8000"]
    depends_on: [kafka]

  alert-router:
    build:
      context: "./Alert Management/alert-router-service"
    image: myregistry.com/deas-la/alert-router-service:latest
    ports: ["8001:8001"]
    depends_on: [kafka]

  delivery:
    build:
      context: "./Delivery-Logging/delivery-service"
    image: myregistry.com/deas-la/delivery-service:latest
    ports: ["8002:8002"]
    depends_on: [kafka]

  logger:
    build:
      context: "./Delivery-Logging/logger-service"
    image: myregistry.com/deas-la/logger-service:latest
    ports: ["8003:8003"]
    depends_on: [mongodb]

  auth:
    build:
      context: "./Delivery-Logging/auth-service"
    image: myregistry.com/deas-la/auth-service:latest
    ports: ["8004:8004"]
