name: CI/CD Pipeline

on:
  push:
    branches: [ test ]      # or main, as you prefer

env:
  REGISTRY: myregistry.com
  REPO_PREFIX: deas-la

jobs:
  build_and_push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push each service
        run: |
          declare -A services=(
            ["alert-generator-service"]="Alert Management/alert-generator-service"
            ["alert-router-service" ]="Alert Management/alert-router-service"
            ["delivery-service"     ]="Delivery-Logging/delivery-service"
            ["logger-service"       ]="Delivery-Logging/logger-service"
            ["auth-service"         ]="Delivery-Logging/auth-service"
          )
          for name in "${!services[@]}"; do
            context="${services[$name]}"
            image="${{ env.REGISTRY }}/${{ env.REPO_PREFIX }}/$name:latest"
            echo "Building $name from $context → $image"
            docker build -t "$image" "$context"
            docker push "$image"
          done

  deploy:
    name: Deploy to EC2 Hosts
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to all EC2 hosts
        run: |
          HOSTS=(
            "${{ secrets.EC2_HOST_ALERT_GENERATOR }}"
            "${{ secrets.EC2_HOST_ALERT_ROUTER }}"
            "${{ secrets.EC2_HOST_DELIVERY }}"
            "${{ secrets.EC2_HOST_LOGGER }}"
            "${{ secrets.EC2_HOST_AUTH }}"
          )

          for host in "${HOSTS[@]}"; do
            echo "→ Deploying to $host"
            scp -o StrictHostKeyChecking=no docker-compose.yml \
               ${{ secrets.EC2_USER }}@$host:~/docker-compose.yml

            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@$host << 'EOF'
              set -e
              # Pull the latest images (no local build)
              docker compose -f ~/docker-compose.yml pull
              # (Re)create all services in detached mode
              docker compose -f ~/docker-compose.yml up -d --no-build
            EOF
          done
