name: CI/CD Pipeline

on:
  push:
    branches: [ test ]

env:
  REGISTRY: docker.io
  NAMESPACE: darkjus
  PROJECT: deas-la

jobs:
  build_and_push:
    # … unchanged …

  deploy:
    name: Deploy to EC2 Hosts
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code          # ← Add this
        uses: actions/checkout@v3

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via Docker Compose on each EC2
        run: |
          HOSTS=(
            "${{ secrets.EC2_HOST_ALERT_GENERATOR }}"
            "${{ secrets.EC2_HOST_ALERT_ROUTER }}"
            "${{ secrets.EC2_HOST_DELIVERY }}"
            "${{ secrets.EC2_HOST_LOGGER }}"
            "${{ secrets.EC2_HOST_AUTH }}"
          )

          for host in "${HOSTS[@]}"; do
            echo "→ Deploying to $host"

            # Copy the unified compose file into the runner workspace
            scp -o StrictHostKeyChecking=no docker-compose.yml \
              ${{ secrets.EC2_USER }}@"$host":~/docker-compose.yml

            # Pull & restart containers on the EC2
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@"$host" \
              "set -e; cd ~; \
               docker compose -f docker-compose.yml pull; \
               docker compose -f docker-compose.yml up -d --no-build"
          done
